steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app/app.yaml']
  env:
    - 'CHUNITHM_SEGA_ID=${_CHUNITHM_SEGA_ID}'
    - 'CHUNITHM_PASSWORD=${_CHUNITHM_PASSWORD}'
    - 'CHUNITHM_GCP_PROJECT=${_CHUNITHM_GCP_PROJECT}'
